from importlib import resources
from pathlib import Path
from typing import Any
import filecmp
import shutil

from .layout import (
    layout_spec_colgap_in,
    layout_spec_fullpage_height_in,
    layout_spec_rowgap_in,
    layout_spec_stacked_height_in,
    normalized_template,
)


PUBIFY_STY_FILENAME = "pubify.sty"
TEX_TEMPLATE_FILENAME = "pubify-template.tex"


def install_pubify_package(destination: str | Path) -> Path:
    """Copy `pubify.sty` into a document directory.

    In normal use, prefer `prepare(...)`, which installs both `pubify.sty` and
    `pubify-template.tex` together.

    Args:
        destination: Directory that should receive `pubify.sty`, or an explicit
            `.sty` destination path.

    Returns:
        The written `pubify.sty` path.
    """
    destination = Path(destination).expanduser()
    if destination.suffix != ".sty":
        destination = destination / PUBIFY_STY_FILENAME

    destination.parent.mkdir(parents=True, exist_ok=True)

    source = resources.files("pubify_tex.assets").joinpath("pubify.sty")
    with resources.as_file(source) as source_path:
        if destination.exists() and filecmp.cmp(source_path, destination, shallow=False):
            return destination
        shutil.copy2(source_path, destination)

    return destination


def write_tex_template(path: str | Path, template: dict[str, Any] | None = None) -> Path:
    """Write `pubify-template.tex` for a document template dictionary.

    In normal use, prefer `prepare(...)`, which writes the template file and
    installs `pubify.sty` in one step.

    Args:
        path: Destination directory or explicit `.tex` file path.
        template: Optional template dictionary. When omitted, the built-in
            default template is used.

    Returns:
        The written `pubify-template.tex` path.
    """
    spec = normalized_template(template)
    colgap_in = layout_spec_colgap_in(spec)
    rowgap_in = layout_spec_rowgap_in(spec)
    fullpage_height_in = layout_spec_fullpage_height_in(spec)
    stacked_height_in = layout_spec_stacked_height_in(spec)

    output_path = Path(path).expanduser()
    if output_path.suffix != ".tex":
        output_path = output_path / TEX_TEMPLATE_FILENAME
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "\n".join(
            [
                "% Generated by pubify-tex. Edit the Python template instead.",
                f"\\setlength{{\\figcolgap}}{{{colgap_in:.5f}in}}",
                f"\\setlength{{\\figcaptionallowance}}{{{spec['caption_allowance_in']:.5f}in}}",
                f"\\providecommand{{\\figbasefontsizept}}{{{spec['base_fontsize_pt']:.5f}}}",
                f"\\setlength{{\\figcaptionlineheight}}{{{spec['caption_lineheight_pt']:.5f}pt}}",
                f"\\setlength{{\\figfullpageheight}}{{{fullpage_height_in:.5f}in}}",
                f"\\setlength{{\\figstackheight}}{{{stacked_height_in:.5f}in}}",
                f"\\setlength{{\\figsubcaptionallowance}}{{{spec['subcaption_allowance_in']:.5f}in}}",
                f"\\setlength{{\\figsubcaptionlineheight}}{{{spec['subcaption_lineheight_pt']:.5f}pt}}",
                f"\\setlength{{\\figsubcaptionskip}}{{{spec['subcaption_skip_in']:.5f}in}}",
                f"\\setlength{{\\figcaptionskip}}{{{spec['caption_skip_in']:.5f}in}}",
                f"\\setlength{{\\figpostcaptionskip}}{{{spec['post_caption_skip_in']:.5f}in}}",
                f"\\setlength{{\\figrowgap}}{{{rowgap_in:.5f}in}}",
                "",
            ]
        )
    )
    return output_path


def prepare(destination: str | Path, template: dict[str, Any] | None = None) -> tuple[Path, Path]:
    """Install the LaTeX-side files for a document directory.

    `prepare(...)` copies `pubify.sty` into `destination` and writes a
    `pubify-template.tex` file there using the provided template values.

    Args:
        destination: Directory that should receive `pubify.sty` and
            `pubify-template.tex`.
        template: Optional template dictionary used to generate
            `pubify-template.tex`.

    Returns:
        A pair `(package_path, template_path)` with the written file paths.
    """
    package_path = install_pubify_package(destination)
    template_path = write_tex_template(destination, template=template)
    return package_path, template_path
